name: Question
description: Ask a question related to the theme
title: "[question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: I have a question regarding the theme
      placeholder: Feel free to ask your question regarding the theme
    validations:
      required: true